---
title: "STATS 401 (Fall 2018) <br>'Applied Statistical Methods II'"
author: "Instructor: Edward L. Ionides"
output:
  html_document:
    theme: flatly
    toc: yes
csl: ecology.csl
---

------

The [syllabus](syllabus.html) gives the course description, contact information, grading scheme, and other course information.

----------

## Class notes 

1. [Getting started](01/notes01.pdf). 
[(R code)](01/notes01.R).
[(Annotations)](01/annotated-notes01.pdf).

2. [Matrices for applied statistics](02/notes02.pdf). 
[(R code)](02/notes02.R).
[(Annotations)](02/annotated-notes02.pdf).

3. [Fitting a linear model to data by least squares](03/notes03.pdf). 
[(R code)](03/notes03.R).
[(Annotations)](03/annotated-notes03.pdf).

4. [Probability models](04/notes04.pdf).
[(R code)](04/notes04.R).
[(Annotations)](04/annotated-notes04.pdf).
 
5. [Vector random variables](05/notes05.pdf).
[(R code)](05/notes05.R).
[(Annotations)](05/annotated-notes05.pdf).

6. [Confidence intervals and hypothesis testing](06/notes06.pdf).
[(R code)](06/notes06.R).
[(Annotations)](06/annotated-notes06.pdf).

7. [Factors and the ANOVA F-test](07/notes07.pdf).
[(R code)](07/notes07.R).
[(Annotations)](07/annotated-notes07.pdf).

    [Discussion: STATS 401 and the future of undergraduate data science](ds/ds.pdf). [(Feedback)](ds/response.pdf).

8. [Model diagnostics](08/notes08.pdf).
[(R code)](08/notes08.R).
[(Annotations)](08/annotated-notes08.pdf).

9. [Additional topics in linear modeling](09/notes09.pdf). 
[(R code)](09/notes09.R).
[(Annotations)](09/annotated-notes09.pdf).


--------

## Homework assignments

* [Homework 0. Setting up your laptop](hw/hw00/hw00.html). 
Due in lab on 9/7.

* [Homework 1. Introduction to R](hw/hw01/hw01.html). 
Due in lab on 9/14.
    * [HW 1 Solutions](hw/hw01/hw01_solutions.html)

* [Homework 2. More swirl and some matrix exercises](hw/hw02/hw02.html). 
Due in lab on 9/21. 
    * [HW 2 Solutions](hw/hw02/hw02_solutions.html)


* [Homework 3. More swirl and fitting a linear model by least squares](hw/hw03/hw03.html). 
Due in lab on 9/28. 
    * [HW 3 Solutions](hw/hw03/hw03_solutions.html)

* [Homework 4. Probability exercises and some summation](hw/hw04/hw04.html). 
Due in lab on 10/5. 
    * [HW 4 Solutions](hw/hw04/hw04_sol.html).


* [Homework 5. Covariance and correlation and symmetric matrices](hw/hw05/hw05.html). 
Due in lab on 10/19. 
    * [HW 5 Solutions](hw/hw05/hw05_solutions.html).

* [Homework 6. The probability model for the linear model](hw/hw06/hw06.html). 
Due in lab on 10/26. 
    * [HW 6 Solutions](hw/hw06/hw6_sols.html).

* [Homework 7. Modeling and data analysis: standard errors, confidence intervals and a binary explanatory variable.](hw/hw07/hw07.html). Due in lab on 11/2.
    * [HW 7 Solutions](hw/hw07/hw07_sol.html).

* [Homework 8. Making predictions and hypothesis tests.](hw/hw08/hw08.html). Due in lab on 11/9.
    * [HW 8 Solutions](hw/hw08/hw08_solutions.html).

* [Homework 9. Kicking goals: linear models with factors.](hw/hw09/hw09.html). Due in lab on 11/16.

<!--
[Solutions](hw/hw09/sol_hw09.html).
-->

* [Homework 10. Making and interpreting an F test.](hw/hw10/hw10.html). Due in lab on 11/30.

<!--
[Solutions](hw/hw09/sol_hw09.html).
-->

* [Homework 11. Data analysis: investigating hospital infections](hw/hw11/hw11.html). Due in lab on 12/7.

<!--
[Solutions](hw/hw11/sol_hw11.html).
-->

------------

## Lab materials

* [STATS 250 Help Card](STATS250 Full Help Card.pdf).

* [Lab 1. Introduction to R](Lab/Lab01/lab01.pdf) Slides for 9/7.
    * [CH01PR19.txt](Lab/Lab01/CH01PR19.txt) Dataset of ACT scores and GPAs of college freshmen.
    * [plastic_hardness.txt](Lab/Lab01/plastic_hardness.txt) Plastic hardness dataset.
    * [Lab 1 Solutions](Lab/Lab01/lab01_solutions.R) Solutions to lab exercises and ticket.


* [Lab 2. Summation Review and Apply()](Lab/Lab02/lab2_w18.pdf). Slides for 9/14.
    * [Lab 2 Solutions](Lab/Lab02/lab02_solutions.R) Solutions to lab ticket.
    
* [Lab 3. Basic Matrix Computations and the Linear Model](Lab/Lab03/lab03.pdf). Slides for 9/21.

* [Lab 4. Summation, Matrix computation and Linear Model Review](Lab/Lab04/lab04.pdf). Slides for 9/28. 
    * [Lab 4 Solutions](Lab/Lab04/lab04_solutions.pdf).

* Lab 5. Quiz 1.

* [Lab 6. Bivariate Random Variables and Covariance](Lab/Lab06/Lab06.pdf). Slides for 10/12.
    * [Lab 6 Solutions](Lab/Lab06/Lab06_solutions.pdf).

* [Lab 7. Probability Model and Covariance Pracitce](Lab/Lab07/Lab07.pdf). Slides for 10/19.
    * (Lab solutions within lab slides.)

* [Lab 8. Confidence intervals](Lab/Lab08/Lab8.pdf). Slides for 10/26.
    * [gpa.txt](Lab/Lab08/gpa.txt).
    * [Lab 8 Solutions](Lab/Lab08/Lab8_solutions.pdf).

* [Lab 9. Hypothesis Testing, Confidence and Prediction Intervals for New Observations](Lab/Lab09/Lab9.pdf). Slides for 11/2.
    * [bottle_2016.csv](Lab/Lab09/bottle_2016.csv).
    * [crime.txt](Lab/Lab09/crime.txt).
    * [Solutions](Lab/Lab09/lab9_solutions.pdf).

* [Lab 10. Factors in the Linear Model](Lab/Lab10/lab10.pdf). Slides for 11/9.

* Lab 11. Quiz 2 and Introduction to R Markdown.
    * [Introduction to R Markdown HTML](Lab/Lab11/R_markdown_Introduction.html)
    * [Introduction to R Markdown PDF](Lab/Lab11/R_markdown_Introduction.pdf)
    * [Code](Lab/Lab11/R_markdown_Introduction.Rmd)

<!--
 [Solutions](lab/lab10/sol_lab10.html).

* Lab 12. Data analysis. [Code](lab/lab12/lab12.R).

* Lab 13. Final review. [Slides](lab/lab13/lab13_slides.pdf) and [exercises](lab/lab13/lab13_exercises.pdf) for 4/12 and 4/13.  [Solutions for the exercises](lab/lab13/lab13_exercises_sol.html)

-->

------------

## Quiz materials

* [Questions in the quiz 1 generator](quiz1/all_quiz1.pdf). [Solutions](quiz1/all_quiz1_sol.pdf).

* [Questions in the quiz 2 generator](quiz2/questions_quiz2.pdf). [Solutions](quiz2/solutions_quiz2.pdf).
 [Sample quiz](quiz2/sample.pdf).

-----------

## Midterm exam materials

* [Practice midterm exam](mt/practice/mt-practice.pdf).
[Solutions](mt/practice/sol_mt-practice.pdf).

* [Midterm exam](mt/mt401f18/paper_mt401f18.pdf).
[Solutions](mt/mt401f18/sol_mt401f18.pdf).
[Histogram of scores](mt/mt401f18/hist_mt401f18.pdf).

-----------

## Final exam materials

<!--

* Topics for the final exam will include

1. F tests.

2. Prediction intervals.

3. Confidence intervals for linear model coefficients.

4. Normal approximations and mean/variance calculations.

5. Linear model diagnostics.

6. Colinearity and its consequences.

7. Building and interpreting design matrices for models with interactions and factors.

8. Observational studies and causation.

-->

* The style and format of the final exam will be based on the practice final exam below. The exam will work through a data analysis, asking questions to requiring understanding of the statistical techniques used, how they are computed, and how they are interpreted.

* [Practice final exam](final/final401w18/final401w18.pdf). [Solutions](final/final401w18/sol_final401w18.pdf). This is a past final exam that includes a question on collinearity which we may or may not cover.

* The final exam will cover all material in Chapters 1-8 of the notes, as well as all homeworks and labs. The material will focus on material after Chapter 5, but this builds closely on Chapters 1-5. Some topics from Chapter 9 will be included, depending on which get covered in class. An announcement will be made later about this.


------------

-----------

