\if \QLABELS1 Q4-4. \fi
Recall the nels88 dataset from lab. 
These data are a subset of the National Education Longitudinal Study of 1988 which examined schoolchildren's performance on a math test score in 8th grade. 
`ses` is the socioeconomic status of parents and `paredu` is the parents highest level of education achieved (less than high school, high school, college, BA, MA, PhD).
`race` determines the race of each student which is one of White, Black, Asian or Hispanic.

```{r lm_nels_anova}
library(faraway)
data(nels88)
head(nels88)
fit <- lm(math ~ ses + paredu + race, data = nels88)
summary(fit)
anova(fit)
```
Suppose we are interested in finding whether the race of the student is associated with their math score, after controlling for the other variables.

(a)  Write out the null and alternative hypothesis for carrying out the above analysis. (Describe all parameters clearly)

(b) What test would you carry out? Clearly explains how the test is constructed, giving relevant formulas. You may define a residual sum of squares in words, without giving an explicit formula.

(c) Report on the conclusions of your test based on the R output provided.

--------------




