
We have been recruited by a California university to explore the relationship between water salinity, water oxygen, and water temperature. We have been given 60 years of oceanographic data collected from the California Current by the California Cooperative Oceanic Fisheries Investigations. Below is a snapshot of the data. (Source: https://www.kaggle.com/sohier/calcofi)

- Depthm: Depth in meters
- T_degC: Water temperture in degrees Celsius
- Salnty: Water Salinity in g of salt per kg of water
- 02ml_L: $O_2$ mixing ratio in ml/L

```{r, echo = F, include = FALSE}
bottle_2016 <- read.csv('bottle_2016.csv', header = TRUE)
```
Now suppose we are interested in predicting the birthweight of a baby who has a 30-year-old white mother with weight 130. 

(a) Specify a row matrix $\vect{x}^*$ so that $\hat y^*=\vect{x}^*\vect{b}$ gives the least square predictor.

(b) Write a matrix expression for the variance of $\hat Y^*=\vect{x}^*\vect{\hat\beta}$ where $\vect{\hat\beta}$ is the least squares fit on model-generated data, i.e., $\vect{\hat\beta}=(\mat{X}^\transpose\mat{X})^{-1}\mat{X}^\transpose \vect{Y}$.

------------

